plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/benny/Desktop/听脑ai/广告数据/asa后端数据"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]