(function(){
var D, rows=[], filtered=[], page=1, PAGE=50, filter='all', chart1=null, chart2=null;
var $=document.getElementById.bind(document);
function n(v){return v==null||isNaN(+v)?0:+v} function fmt(v,d){return v==null||isNaN(+v)?'—':(+v).toLocaleString('en-US',{maximumFractionDigits:d==null?0:d})} function cny(v){return v==null||isNaN(+v)?'—':'¥'+(+v).toLocaleString('en-US',{maximumFractionDigits:2})} function pct(v){return v==null||isNaN(+v)?'—':(+v*100).toFixed(2)+'%'}
function sum(arr){var t={支出:0,展示次数:0,点击次数:0,安装次数:0,激活数:0,注册人数:0,总充值金额:0}; arr.forEach(function(r){Object.keys(t).forEach(function(k){t[k]+=n(r[k])})}); t.点击率=t.展示次数?t.点击次数/t.展示次数:0; t.安装率=t.点击次数?t.安装次数/t.点击次数:0; t.激活率=t.安装次数?t.激活数/t.安装次数:0; t.注册率=t.激活数?t.注册人数/t.激活数:0; t.安装成本=t.安装次数?t.支出/t.安装次数:null; t.注册成本=t.注册人数?t.支出/t.注册人数:null; t.roi=t.支出?t.总充值金额/t.支出:0; return t}
function setKPIs(){var t=D.total,b=D.brand,nb=D.nonbrand; $('genAt').textContent=D.meta.generated_at+'；数据 '+D.meta.date_min+'~'+D.meta.date_max+'；匹配 '+D.meta.matched_rows+'/'+D.meta.merged_rows; $('kSpend').textContent=cny(t.支出); $('kSpendSub').textContent='展示 '+fmt(t.展示次数)+'｜点击 '+fmt(t.点击次数); $('kInstall').textContent=fmt(t.安装次数); $('kInstallSub').textContent='安装率 '+pct(t.安装率); $('kReg').textContent=fmt(t.注册人数); $('kRegSub').textContent='注册率 '+pct(t.注册率); $('kRev').textContent=cny(t.总充值金额); $('kRevSub').textContent='ROI '+pct(t.roi); $('kCost').textContent=cny(t.注册成本); $('kCostSub').textContent='品牌 '+cny(b.注册成本)+'｜非品牌 '+cny(nb.注册成本); box('brandBox',b); box('nonbrandBox',nb)}
function box(id,t){$(id).innerHTML=[['支出',cny(t.支出)],['安装',fmt(t.安装次数)],['激活',fmt(t.激活数)],['注册',fmt(t.注册人数)],['充值',cny(t.总充值金额)],['安装成本',cny(t.安装成本)],['注册成本',cny(t.注册成本)],['ROI',pct(t.roi)]].map(function(x){return '<div class="metric"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>'}).join('')}
function charts(){var d=D.daily, labels=d.map(x=>x.date); if(chart1)chart1.destroy(); if(chart2)chart2.destroy(); chart1=new Chart($('c1'),{type:'line',data:{labels:labels,datasets:[{label:'支出',data:d.map(x=>n(x.支出)),borderColor:'#58a6ff',yAxisID:'y',tension:.3},{label:'注册',data:d.map(x=>n(x.注册人数)),borderColor:'#3fb950',yAxisID:'y1',tension:.3},{label:'充值',data:d.map(x=>n(x.总充值金额)),borderColor:'#d29922',yAxisID:'y',tension:.3}]},options:{responsive:true,scales:{y:{position:'left'},y1:{position:'right',grid:{drawOnChartArea:false}}}}}); chart2=new Chart($('c2'),{type:'line',data:{labels:labels,datasets:[{label:'注册成本',data:d.map(x=>x.注册成本),borderColor:'#f85149',yAxisID:'y',tension:.3},{label:'ROI',data:d.map(x=>n(x.roi)),borderColor:'#d29922',yAxisID:'y1',tension:.3}]},options:{responsive:true,scales:{y:{position:'left'},y1:{position:'right',grid:{drawOnChartArea:false}}}}})}
function apply(){var q=$('q').value.trim().toLowerCase(); filtered=rows.filter(function(r){ if(filter==='brand'&&r.词类!=='品牌词')return false; if(filter==='nonbrand'&&r.词类!=='非品牌词')return false; if(filter==='7d'){var ds=[...new Set(rows.map(x=>x.date))].sort().slice(-7); if(ds.indexOf(r.date)<0)return false} if(filter==='month'){var ds=[...new Set(rows.map(x=>x.date))].sort().slice(-31); if(ds.indexOf(r.date)<0)return false} if(q&&String(r.关键词).toLowerCase().indexOf(q)<0)return false; return true}); var col=$('sort').value; filtered.sort(function(a,b){var av=n(a[col]),bv=n(b[col]); if(col==='注册成本') return (av||1e12)-(bv||1e12); return bv-av}); render()}
function render(){var total=Math.max(1,Math.ceil(filtered.length/PAGE)); if(page>total)page=total; var start=(page-1)*PAGE, part=filtered.slice(start,start+PAGE); $('count').textContent=filtered.length; $('page').textContent=page+' / '+total; $('tb').innerHTML=part.map(function(r){return tr(r)}).join('')||'<tr><td colspan="16">暂无数据</td></tr>'; $('tf').innerHTML=tr(sum(filtered),'合计'); $('prev').disabled=page<=1; $('next').disabled=page>=total}
function tr(r,label){var name=label || r['关键词'] || r.keyword || '—'; var type=r['词类'] || ''; var cls=type==='品牌词'?'<span class="bdg b">品牌</span>':'<span class="bdg nb">非品牌</span>'; var roi=n(r.roi); return '<tr><td>'+name+'</td><td>'+cls+'</td><td>'+cny(r['支出'])+'</td><td>'+fmt(r['展示次数'])+'</td><td>'+fmt(r['点击次数'])+'</td><td>'+fmt(r['安装次数'])+'</td><td>'+fmt(r['激活数'])+'</td><td>'+fmt(r['注册人数'])+'</td><td>'+cny(r['总充值金额'])+'</td><td>'+cny(r['安装成本'])+'</td><td>'+cny(r['注册成本'])+'</td><td>'+pct(r['点击率'])+'</td><td>'+pct(r['安装率'])+'</td><td>'+pct(r['激活率'])+'</td><td>'+pct(r['注册率'])+'</td><td class="'+(roi>=1?'pos':'neg')+'">'+pct(roi)+'</td></tr>'}
function csv(){var cols=['关键词','词类','支出','展示次数','点击次数','安装次数','激活数','注册人数','总充值金额','安装成本','注册成本','点击率','安装率','激活率','注册率','roi']; var lines=[cols.join(',')].concat(filtered.map(r=>cols.map(c=>'"'+String(r[c]??'').replace(/"/g,'""')+'"').join(','))); var a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'})); a.download='keyword_backend_export.csv'; a.click()}
fetch('keyword_backend_data.json?v='+Date.now()).then(r=>r.json()).then(function(d){D=d; rows=d.keywords; setKPIs(); charts(); apply();});
document.addEventListener('click',function(e){var b=e.target.closest('button[data-f]'); if(b){document.querySelectorAll('button[data-f]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); filter=b.dataset.f; page=1; apply()} if(e.target.id==='prev'){page--;render()} if(e.target.id==='next'){page++;render()} if(e.target.id==='csv')csv()}); $('q').addEventListener('input',function(){page=1;apply()}); $('sort').addEventListener('change',function(){page=1;apply()});
})();